apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 033052248722.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 033052248722.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: edd4c62f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
